### ISSUE TITLE
SALTSTACK-GPG-KEY.pub fails through http from http://repo.saltstack.com

### ISSUE THREAD

**Issue by boopalans** [pndaproject/pnda-heat-templates#121]
Getting salt stack key from 
http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.8.11/SALTSTACK-GPG-KEY.pub
 and 
http://repo.saltstack.com/apt/ubuntu/14.04/amd64/archive/2015.8.11/ trusty main

is failing, if the the company infrastructure not allowed http, but https is working. 

Issue : 
https://github.com/pndaproject/pnda-heat-templates/blob/develop/scripts/package_install.sh#L13

Fix : 
Change http to https.

**Comment by trsmith2** [comment]
Fixed by https://github.com/pndaproject/pnda-heat-templates/pull/122
