### ISSUE TITLE
Pnda stack completed sucessfully, but errors in the logs

### ISSUE THREAD

**Issue by nfss83** [pndaproject/pnda-heat-templates#124]
Hi,

I created pnda stack successfully using OpenStack. When finished the command "./heat_cli.py -e cation -f pico -s pnda_key create -o 1 -n 1 -k 1 -z1", the terminal showed the message "Stack CREATE completed successfully". I can access the  nodes via SSH and  can connect to the PNDA console (via http). But I checked the logs and found some errors. How can I solve them? Or are these errors not important?

Logs: https://pastebin.com/4jqgY0mQ

Pnda: Release 3.5
OpenStack: Mitaka (Devstack) installed on Ubuntu 16.04   Hardware: 72 GB RAM, 32 cpu, 500 GB.
Installation client: Ubuntu Server 14.04

**Comment by trsmith2** [comment]
Looks like the cluster didn't get created properly, and that the error is related to the mirror build. See kafka-install-kafka-dist in the logs.

**Comment by nfss83** [comment]
Thanks for your answer. I created the mirror again, apparently without errors. But when I tried to deploy the Pnda Cluster, I hit one error with the kafka package. I uploaded manually the Kafka package and its sha1  to the mirror server.  Now, the Pnda stack completed successfully without errors.

**Comment by trsmith2** [comment]
We've fixed an issue today caused by Kafka archives moving around on the mirrors - so I think that probably accounts for the most recent hiccup. Glad you got it working!
