### ISSUE TITLE
Platform salt Branch option is not in heat-template-yaml file

### ISSUE THREAD

**Issue by boopalans** [pndaproject/pnda-heat-templates#125]
Now, the platform salt branch details are passed in command line. If not, it takes master branch. Need to add branch in the pnda_env.yaml file.

**Comment by trsmith2** [comment]
Already supported, see GitBranch.

**Comment by smaniramkrish** [comment]
Trevor the request is to support the option yaml.file similar to AWS. Currently, it is supported as part heat-cli option. This is raised in order to have same workflow b/w heat and aws

**Comment by trsmith2** [comment]
It's already supported in the YAML - if you mean to add it to the example, I agree
