### ISSUE TITLE
Error validating value 'trusty-pnda-cloud-user-software-config-mirror': No images matching

### ISSUE THREAD

**Issue by 10186937** [pndaproject/pnda-heat-templates#4]
Hi,
I comment the `dns_nameservers`in `pnda_env_standard.yaml`, but another error I get:
`JSON response : {"explanation": "The server could not comply with the request since it is either malformed or otherwise incorrect.", "code": 400, "error": **{"message": "Property error: : resources.saltmaster_server.properties.image: : Error validating value 'trusty-pnda-cloud-user-software-config-mirror': No images matching {'name': u'trusty-pnda-cloud-user-software-config-mirror'}. (HTTP 404)"**, "traceback": "Traceback (most recent call last):\n\n  File \"/opt/stack/heat/heat/common/context.py\", line 424, in wrapped\n    return func(self, ctx, *args, **kwargs)\n\n  File \"/opt/stack/heat/heat/engine/service.py\", line 823, in create_stack\n    template_id)\n\n  File \"/opt/stack/heat/heat/engine/service.py\", line 698, in _parse_template_and_validate_stack\n    stack.validate()\n\n  File \"/usr/lib/python2.7/site-packages/osprofiler/profiler.py\", line 147, in wrapper\n    return f(*args, **kwargs)\n\n  File \"/opt/stack/heat/heat/engine/stack.py\", line 802, in validate\n    result = res.validate()\n\n  File \"/opt/stack/heat/heat/engine/resources/openstack/nova/server.py\", line 1391, in validate\n    super(Server, self).validate()\n\n  File \"/opt/stack/heat/heat/engine/resource.py\", line 1449, in validate\n    return self.validate_template()\n\n  File \"/opt/stack/heat/heat/engine/resource.py\", line 1480, in validate_template\n    message=ex.error_message)\n\nStackValidationFailed: Property error: resources.saltmaster_server.properties.image: Error validating value 'trusty-pnda-cloud-user-software-config-mirror': No images matching {'name': u'trusty-pnda-cloud-user-software-config-mirror'}. (HTTP 404)\n", "type": "StackValidationFailed"}, "title": "Bad Request"} from (pid=4927) to_json /opt/stack/heat/heat/common/serializers.py:40`
What should I config or where can I get the image?
Thank you!

**Comment by jgarnier** [comment]
have a look at [building OS image for PNDA](https://github.com/pndaproject/pnda-dib-elements)
